version: "3.8"
services:
 controller:
   container_name: controller
   build:
     context: ./
     dockerfile: dockerfiles/contDockerfile
     args:
       RSA: keys/con_rsa
       PUB: keys/con_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   restart: always
   stdin_open: true
   command: bash

 ansible1:
   container_name: ansible1
   build:
     context: ./
     dockerfile: dockerfiles/hostDockerfile
     args:
       RSA: keys/a1_rsa
       PUB: keys/a1_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   depends_on:
     - controller
   restart: always
   stdin_open: true
   command: bash

 ansible2:
   container_name: ansible2
   build:
     context: ./
     dockerfile: dockerfiles/hostDockerfile
     args:
       RSA: keys/a2_rsa
       PUB: keys/a2_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   depends_on:
     - controller
   restart: always
   stdin_open: true
   command: bash

networks:
  ansible_net:
