version: "3.8"
services:
 controller:
   container_name: controller
   build:
     context: ./
     dockerfile: Dockerfile
     args:
       RSA: con_rsa
       PUB: con_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   restart: always
   stdin_open: true
   command: bash

 ansible1:
   container_name: ansible1
   build:
     context: ./
     dockerfile: Dockerfile
     args:
       RSA: a1_rsa
       PUB: a1_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   depends_on:
     - controller
   restart: always
   stdin_open: true
   command: bash

 ansible2:
   container_name: ansible2
   build:
     context: ./
     dockerfile: Dockerfile
     args:
       RSA: a2_rsa
       PUB: a2_rsa.pub
   environment:
     - "ANSIBLE_USER:ansible"
     - "ANSIBLE_PWD:!ansibl3"
   networks:
     - ansible_net
   depends_on:
     - controller
   restart: always
   stdin_open: true
   command: bash

networks:
  ansible_net:
